"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['bluetoothserver.py']
DATA_FILES = []
OPTIONS = {"argv_emulation": False,
           "compressed": True,
           "optimize": 2,
           "iconfile": "remote_bt_6464.icns"}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
